---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: in-cluster
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - https://github.com/rknaus/argocd-gitops
