---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-argocd
  namespace: argocd
spec:
  description: "This policy allows all traffic within the namespace"
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": argocd
    - fromEndpoints:
        - matchExpressions:
            - key: reserved:ingress
              operator: Exists
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": argocd
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEntities:
        - kube-apiserver
    - toFQDNs:
        - matchName: github.com
        - matchName: bitnami-labs.github.io
        - matchName: release-assets.githubusercontent.com
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP

