---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-default
  namespace: default
spec:
  description: "This policy allows all traffic within the namespace"
  endpointSelector:
    matchLabels: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": default
    - fromEndpoints:
        - matchExpressions:
            - key: reserved:ingress
              operator: Exists
  egress:
    - toEndpoints:
        - matchLabels:
            "k8s:io.kubernetes.pod.namespace": default
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
    - toEntities:
        - kube-apiserver
