---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-base-policies
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: cluster-infrastructure
  source:
    repoURL: https://github.com/rknaus/argocd-gitops
    targetRevision: HEAD
    path: apps/cilium-base-policies
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
