---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: example-app
  project: cluster-infrastructure
  source:
    repoURL: https://github.com/rknaus/argocd-gitops
    targetRevision: HEAD
    path: apps/example-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
