---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: external-dns
  project: cluster-infrastructure
  source:
    repoURL: https://github.com/rknaus/argocd-gitops
    chart: sealed-secrets-mikrotik
    targetRevision: feature/external-dns
    path: apps/external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
